//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpanceApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class expance
    {
        public int expid { get; set; }
        public string exptitle { get; set; }
        public string expdescription { get; set; }
        public string expcategory { get; set; }
        public int expamount { get; set; }
        public int catid { get; set; }
        public System.DateTimeOffset expdatetime { get; set; }
    
        public virtual category category { get; set; }
    }
}
